import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Header from "@/components/header";
import Section from "@/components/Section";
import Main from "@/components/main";

export default function Home() {
  return (
    <>
      <Head>
        <title>condoPay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={styles.content}>
        <Section />
        <Main />
      </div>

      <footer className={styles.footer}></footer>
    </>
  );
}
